version: '3'


services:
  couch:
    image: quay.io/mtek/couchdb:2.1.1
    network_mode: default
    environment:
      - COUCHDB_HTTP_BIND_ADDRESS=0.0.0.0
      - COUCHDB_HTTP_PORT=5984
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
